project:
  type: book

book:
  title: "quarto-test-book"
  author: "Jane Doe"
  date: "7/20/2021"
  chapters:
    - index.qmd
    - intro.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
